trigger:
  - main
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'AWS MundosE'
      manifests: 'nginx-deployment.yaml'
